### ISSUE TITLE
Adding more than 1 attribute tag

### ISSUE THREAD

**Issue by 9Lambda** [SIL0RAK/convert-react-to-web-component#17]
Is it possible to pass more than 1 attribute tag? I have tried passing more than 1 into the array however seems to return undefined.

**Comment by SIL0RAK** [comment]
Hi, yes it is possible, could you provide example of your code ?

**Comment by 9Lambda** [comment]
Sure, what I am trying to do is that I have an existing React application and wish to convert/wrap as a web component to be used by another parent application. This fragment application is rendered for a particular route and takes in props from the parent application like so:

```
			<fragment-application
						age={60}
						firstName="tom"
						lastName="smith"
			/>
```

In the fragment-application `index.js` I have:
```

import App from "./App";

reactToWebComponent(App,["age"],'fragment-application' )
```

this works however when I try to pass in more tags it doesn't seem to work like so:
`reactToWebComponent(App,["age","lastName","firstName"],'fragment-application' )`. 

This is what I see when I try to log:
<img width="162" alt="Screen Shot 2022-05-24 at 6 39 34 pm" src="https://user-images.githubusercontent.com/55907842/169988862-74a93661-1d6c-4629-994a-d4358d209b11.png">

Thanks

**Comment by SIL0RAK** [comment]
[This is example of passing multiple parameters (parent application is angular)](https://codesandbox.io/s/convert-react-to-web-component-1qigb)

What framework is your parent application using ?

**Comment by SIL0RAK** [comment]
Ok I think i know the issue. Try to change prop names to fully lover case:

firstName => firstname
lastName => lastname

I will create MR for this issue.

**Comment by 9Lambda** [comment]
Sweet, thanks for taking a look into that and for quickly responding! This library has really helped me.

Also, I'm not sure what the best way to ask questions is so please let me know if there is a better way but I wanted to ask in the `create.ts` file which essentially creates the web component there isn't a shadow DOM element added to it. Does this conversion library to web component not have that bit?

**Comment by SIL0RAK** [comment]
No it does not create shadow DOM it directly attaches react component to web component.
Will add this functionality with upcoming major version.

**Comment by 9Lambda** [comment]
Awesome, thank you so much for the help!

**Comment by 9Lambda** [comment]
hi @SIL0RAK , following up our thread above is there an expected time frame to add the shadow DOM functionality in the major version update? Just asking as I would like to use this library for a project Im working on.

**Comment by SIL0RAK** [comment]
I think i will test it and release it by the end of the week
